//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreservedMoose.SpecFlowHarness
{
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PreservedMoose.SpecFlowHarness.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The &apos;{0}&apos; method could not be found..
		/// </summary>
		internal static string BaseStepRow_MethodInfo
		{
			get
			{
				return ResourceManager.GetString("BaseStepRow_MethodInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Could not translate column &apos;{0}&apos; on class &apos;{1}&apos;. The class/struct does not provide a default constructor..
		/// </summary>
		internal static string BaseStepRow_MethodInfoConstructorCheck
		{
			get
			{
				return ResourceManager.GetString("BaseStepRow_MethodInfoConstructorCheck", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Could not translate column &apos;{0}&apos; on class &apos;{1}&apos;. The class/struct does not support the ITryParseConverter interface..
		/// </summary>
		internal static string BaseStepRow_MethodInfoConverterCheck
		{
			get
			{
				return ResourceManager.GetString("BaseStepRow_MethodInfoConverterCheck", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Could not find column(s) &apos;{0}&apos; on class &apos;{1}&apos;..
		/// </summary>
		internal static string BaseStepRow_MissingColumnsCheck
		{
			get
			{
				return ResourceManager.GetString("BaseStepRow_MissingColumnsCheck", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Could not translate column(s) &apos;{0}&apos; on class &apos;{1}&apos;. Nullable types are not supported..
		/// </summary>
		internal static string BaseStepRow_NullableTypesCheck
		{
			get
			{
				return ResourceManager.GetString("BaseStepRow_NullableTypesCheck", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid value &apos;{0}&apos; for type &apos;{1}&apos;..
		/// </summary>
		internal static string Converter_InvalidValue
		{
			get
			{
				return ResourceManager.GetString("Converter_InvalidValue", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Null or empty string for type &apos;{0}&apos;..
		/// </summary>
		internal static string Converter_NullOrEmptyString
		{
			get
			{
				return ResourceManager.GetString("Converter_NullOrEmptyString", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Column &apos;{0}&apos; has invalid value &apos;{1}&apos; for type {2}..
		/// </summary>
		internal static string Parser_InvalidValue
		{
			get
			{
				return ResourceManager.GetString("Parser_InvalidValue", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The &apos;{0}&apos; collection property could not be found!.
		/// </summary>
		internal static string StepRow_CollectionPropertyNotFound
		{
			get
			{
				return ResourceManager.GetString("StepRow_CollectionPropertyNotFound", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Could not create an instance of the class &apos;{0}&apos;..
		/// </summary>
		internal static string StepRow_CouldNotCreateInstance
		{
			get
			{
				return ResourceManager.GetString("StepRow_CouldNotCreateInstance", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The row has not been provided or is of the wrong type..
		/// </summary>
		internal static string StepRow_EqualsOverrideNullMessage
		{
			get
			{
				return ResourceManager.GetString("StepRow_EqualsOverrideNullMessage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The {1} for &apos;{0}&apos; was not set..
		/// </summary>
		internal static string StepRow_ValidationFieldNotSet
		{
			get
			{
				return ResourceManager.GetString("StepRow_ValidationFieldNotSet", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Actual results:.
		/// </summary>
		internal static string StepRowExtensions_CompareActualResults
		{
			get
			{
				return ResourceManager.GetString("StepRowExtensions_CompareActualResults", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The collections are different..
		/// </summary>
		internal static string StepRowExtensions_CompareCollectionsAreDifferent
		{
			get
			{
				return ResourceManager.GetString("StepRowExtensions_CompareCollectionsAreDifferent", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to WARNING: This step is using the Continue On Error feature..
		/// </summary>
		internal static string StepRowExtensions_CompareContinueOnErrorWarning
		{
			get
			{
				return ResourceManager.GetString("StepRowExtensions_CompareContinueOnErrorWarning", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Expected results:.
		/// </summary>
		internal static string StepRowExtensions_CompareExpectedResults
		{
			get
			{
				return ResourceManager.GetString("StepRowExtensions_CompareExpectedResults", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The first collection is undefined..
		/// </summary>
		internal static string StepRowExtensions_CompareFirstCollectionUndefined
		{
			get
			{
				return ResourceManager.GetString("StepRowExtensions_CompareFirstCollectionUndefined", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The second collection is undefined..
		/// </summary>
		internal static string StepRowExtensions_CompareSecondCollectionUndefined
		{
			get
			{
				return ResourceManager.GetString("StepRowExtensions_CompareSecondCollectionUndefined", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to There were errors encountered parsing the table rows for this class:.
		/// </summary>
		internal static string StepRowExtensions_TableParsingErrorMessage
		{
			get
			{
				return ResourceManager.GetString("StepRowExtensions_TableParsingErrorMessage", resourceCulture);
			}
		}
	}
}
